version: '3.8'

services:
  ml-api:
    build:
      context: .                 
      dockerfile: Dockerfile       
    image: ml-api-client        
    container_name: ml_api_container  
    ports:
      - "8000:8000"        
    volumes:
      - ./data:/app/data                
      - ./output:/app/output      
    environment:         
      - MODEL_PATH=/app/output/models 
      - API_KEY=6b8e92be-fc0a-4db5-b8dc-c35dc05d1108
    restart: unless-stopped  